---
authors:
  - Dettonville Development Team
  - "Lee Johnson - ljohnson@dettonville.com"
description:
  Ansible Collection with utilities to ease the management, manipulation,
  and validation of data within a playbook
issues: https://github.com/dettonville/ansible-dettonville-utils/issues
license_file: LICENSE
name: utils
namespace: dettonville
readme: README.md
repository: https://github.com/dettonville/ansible-dettonville-utils
tags:
  - linux
  - utilities
  - data
  - utils
version: 2025.3.19
